#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d II I III IV V VI VII VIII IX X
#Antes
#bspc config border_width         0.5
 #bspc config window_gap          8
#bspc config top_padding 0.5
#bspc config split_ratio          0.5
#bspc config borderless_monocle   false
#bspc config gapless_monocle      false


bspc config border_width         1
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config border_radius 10
bspc config bottom_padding 0
bspc config top_padding 1

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
#AUTOSTART
killall "sxhkd"
killall "picom"
sxhkd -c &
picom &
killall "polybar"
killall "conky" 
#polybar bytee &
#polybar bytee2 &
#polybar -c /home/edgardoyoliani/.config/polybar/placidity-plus/config.ini main &
conky &
polybar -c /home/guarapolabs/.config/polybar/config.ini -rq bar &

#polybar example
#Custom
bspc config focus_follows_pointer true
xrandr --primary --output  HDMI-A-0 --mode 3286x1080 --rotate normal  --rate 75.00 
xrandr --output eDP --mode 1366x768 --rotate normal  --brightness 1.0 --left-of HDMI-A-0 
bspc monitor eDP -d I II III IV V 
bspc monitor HDMI-A-0 -d VI VII VII IX 0 



#Windows rules
bspc rule -a Pavucontrol state=floating rectangle 800x800+50+50 sticky=off

#~/.config/polybar/./launch.sh
#~/.scripts/./start_conky.sh
feh --bg-fill /home/guarapolabs/.dotfile/wallpapers/galaxia_2560x1600_xtrafondos.com.jpg
#nitrogen --restore &
#xwinwrap -g 1920x1080 -ov -- mpv -wid WID ~/.wallpapers/water.mp4
xsetroot -cursor_name left_ptr &
picom --experimental-backends &
bspc config border_with 0.3
setxkbmap -option grp:alt_shift_toggle es,us &
